version: "3.7"
services:
  app:
    networks:
    - phil_network
    image: nginx
    volumes:
    - .:/usr/share/nginx/html
    ports:
    - "80"

networks:
  phil_network: 
    external:
      name: phil_network_default